spring.main.web-application-type: none
spring.profiles.active: local

quiz.app.service:
  dataSource:
    driverClassName: driver-class-name
    url: db-url
    username: db-username
    password: db-username
    schema: application-schema-name

spring.datasource.initialization-mode: always
logging.level.org.springframework.boot.context.properties: DEBUG